<?php

namespace Proxies\__CG__\FM\TTBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Project extends \FM\TTBundle\Entity\Project implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setUser(\FM\TTBundle\Entity\User $user = NULL)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function addPack(\FM\TTBundle\Entity\Pack $packs)
    {
        $this->__load();
        return parent::addPack($packs);
    }

    public function removePack(\FM\TTBundle\Entity\Pack $packs)
    {
        $this->__load();
        return parent::removePack($packs);
    }

    public function getPacks()
    {
        $this->__load();
        return parent::getPacks();
    }

    public function addContext(\FM\TTBundle\Entity\Context $contexts)
    {
        $this->__load();
        return parent::addContext($contexts);
    }

    public function removeContext(\FM\TTBundle\Entity\Context $contexts)
    {
        $this->__load();
        return parent::removeContext($contexts);
    }

    public function getContexts()
    {
        $this->__load();
        return parent::getContexts();
    }

    public function addDomain(\FM\TTBundle\Entity\Domain $domains)
    {
        $this->__load();
        return parent::addDomain($domains);
    }

    public function removeDomain(\FM\TTBundle\Entity\Domain $domains)
    {
        $this->__load();
        return parent::removeDomain($domains);
    }

    public function getDomains()
    {
        $this->__load();
        return parent::getDomains();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'user', 'packs', 'contexts', 'domains');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}